"use client";

import { useFormStore } from "@/store/formStore";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

export default function CreateFormPage() {
  const router = useRouter();
  const initialFormData = useFormStore.getState().formData; // Get initial state directly

  useEffect(() => {
    const createNewForm = async () => {
      // 1. Reset the local state to a blank template, but get the data
      //    This is important for getting a fresh form structure with a new ID
      useFormStore.getState().resetForm();
      const newFormData = useFormStore.getState().formData;

      // 2. Insert the new form into the database
      const { data, error } = await supabase
        .from('forms')
        .insert({
          // The form's UUID will be generated by the database by default
          title: newFormData.title,
          description: newFormData.description,
          form_data: newFormData, // Save the entire form structure
          status: 'draft',
        })
        .select('id') // Return the ID of the new row
        .single();

      if (error) {
        console.error("Error creating new form:", error);
        // Redirect to dashboard on error
        router.push("/dashboard");
      } else if (data) {
        // 3. Redirect to the new editor page for the created form
        router.replace(`/editor/${data.id}`);
      }
    };

    createNewForm();
  }, [router]);

  return (
    <div className="min-h-screen flex items-center justify-center">
      <p>Creating a new form...</p>
    </div>
  );
}
